name: Build Status

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Gauge
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install Raku
      uses: Raku/setup-raku@v1
    - name: Install App::Prove6
      run: zef install --/test App::Prove6
    - name: Test
      run: prove6 -l t
