name: Build Status

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Gauge
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install Raku
      uses: Raku/setup-raku@v1
    - name: Run tests
      run: raku -Ilib t/*.rakutest
